# Build
FROM node:22-bookworm AS build

ARG DB_HOST
ARG DB_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

WORKDIR /app

COPY package.json .

COPY entrypoint.sh .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

# Runtime
FROM node:22-bookworm AS runtime

ARG DB_HOST
ARG DB_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

EXPOSE 3000/tcp

WORKDIR /app

COPY --from=build /app/ .
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
